# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development: 
  adapter: mysql2
  database: reservester_development
  host: localhost
  username: root
  password: password
  port: 3000
  encoding: utf8

test:
  adapter: mysql2
  database: reservester_test
  host: localhost
  username: root
  password: password
  port: 3000
  encoding: utf8

production:
  adapter: postgresql
  encoding: unicode
  database: reservester_production
  username: slopeofhope81
  pool: 5
