
development: 
  adapter: mysql2
  database: reservester_development
  host: localhost
  username: root
  password: password
  port: 3000
  encoding: utf8

test:
  adapter: mysql2
  database: reservester_test
  host: localhost
  username: root
  password: 
  port: 3000
  encoding: utf8

production:
  adapter: postgresql
  encoding: unicode
  database: reservester_production
